apiVersion: apps/v1
kind: Deployment
metadata:
  name: profiles-app-s18
  labels:
    app: profiles-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: profiles-app
  template:
    metadata:
      labels:
        app: profiles-app
    spec:
      containers:
        - name: profiles-container
          image: profiles-app:latest 
          ports:
            - containerPort: 8125
          livenessProbe:
            httpGet:
              path: /
              port: 8125
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 8125
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
