events {}

http {

    # группа серверов, куда Nginx может пересылать запросы
    upstream tasks-svc-s18 {   
        server tasks-svc-s18:8216;  
    }

    upstream service2 {     
        server service2:8000;  
    }

    server {  # виртуальный хост, принимает входящие HTTP‑запросы
        listen 80;  # слушаем порт 80 внутри контейнера Nginx


        # маршрутизация: прокидываем запросы к нужному backend‑сервису
        location /api/tasks {  # все запросы с префиксом /api/tasks
            proxy_pass http://tasks-svc-s18/tasks;  # отправляем в сервис задач
        }

        location /api/other {  # все запросы с префиксом /api/other
            proxy_pass http://service2/other;  # отправляем во второй сервис
        }

    }

}