events {}

http {
    upstream tasks-svc {
        server tasks-svc-s18:8216;
    }
    upstream service2 {
        server service2:8000;
    }

    server {
        listen 80;

        location = / {
            return 302 /shop;
        }

        location /shop {
            proxy_pass http://tasks-svc;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api {
            proxy_pass http://tasks-svc;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /other {
            proxy_pass http://service2;
            proxy_set_header Host $host;
        }
    }
}