# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\x08likes.v1\"#\n\x11\x43reateLikeRequest\x12\x0e\n\x06target\x18\x01 \x01(\t\"0\n\x12\x43reateLikeResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06target\x18\x02 \x01(\t\"\x1c\n\x0eGetLikeRequest\x12\n\n\x02id\x18\x01 \x01(\t\"-\n\x0fGetLikeResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06target\x18\x02 \x01(\t2\x97\x01\n\x0cLikesService\x12G\n\nCreateLike\x12\x1b.likes.v1.CreateLikeRequest\x1a\x1c.likes.v1.CreateLikeResponse\x12>\n\x07GetLike\x12\x18.likes.v1.GetLikeRequest\x1a\x19.likes.v1.GetLikeResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CREATELIKEREQUEST']._serialized_start=27
  _globals['_CREATELIKEREQUEST']._serialized_end=62
  _globals['_CREATELIKERESPONSE']._serialized_start=64
  _globals['_CREATELIKERESPONSE']._serialized_end=112
  _globals['_GETLIKEREQUEST']._serialized_start=114
  _globals['_GETLIKEREQUEST']._serialized_end=142
  _globals['_GETLIKERESPONSE']._serialized_start=144
  _globals['_GETLIKERESPONSE']._serialized_end=189
  _globals['_LIKESSERVICE']._serialized_start=192
  _globals['_LIKESSERVICE']._serialized_end=343
# @@protoc_insertion_point(module_scope)
