version: "3.9"

services:

  likes-svc-s18:
    build: ./starter
    container_name: likes-svc-s18
    ports:
      - "8174:8174"
    restart: always

  likes-rest-s18:
    build: ./starter
    container_name: likes-rest-s18
    command: ["uvicorn", "rest_app:app", "--host", "0.0.0.0", "--port", "8080"]
    ports:
      - "8080:8080"
    restart: always
