# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import service_pb2 as service__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LikesServiceStub(object):
    """gRPC сервис
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateLike = channel.unary_unary(
                '/likes.v2.LikesService/CreateLike',
                request_serializer=service__pb2.CreateLikeRequest.SerializeToString,
                response_deserializer=service__pb2.CreateLikeResponse.FromString,
                _registered_method=True)
        self.GetLike = channel.unary_unary(
                '/likes.v2.LikesService/GetLike',
                request_serializer=service__pb2.GetLikeRequest.SerializeToString,
                response_deserializer=service__pb2.GetLikeResponse.FromString,
                _registered_method=True)
        self.SubscribeLikes = channel.unary_stream(
                '/likes.v2.LikesService/SubscribeLikes',
                request_serializer=service__pb2.SubscribeRequest.SerializeToString,
                response_deserializer=service__pb2.LikeUpdate.FromString,
                _registered_method=True)


class LikesServiceServicer(object):
    """gRPC сервис
    """

    def CreateLike(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLike(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeLikes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LikesServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateLike': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateLike,
                    request_deserializer=service__pb2.CreateLikeRequest.FromString,
                    response_serializer=service__pb2.CreateLikeResponse.SerializeToString,
            ),
            'GetLike': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLike,
                    request_deserializer=service__pb2.GetLikeRequest.FromString,
                    response_serializer=service__pb2.GetLikeResponse.SerializeToString,
            ),
            'SubscribeLikes': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeLikes,
                    request_deserializer=service__pb2.SubscribeRequest.FromString,
                    response_serializer=service__pb2.LikeUpdate.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'likes.v2.LikesService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('likes.v2.LikesService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LikesService(object):
    """gRPC сервис
    """

    @staticmethod
    def CreateLike(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/likes.v2.LikesService/CreateLike',
            service__pb2.CreateLikeRequest.SerializeToString,
            service__pb2.CreateLikeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLike(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/likes.v2.LikesService/GetLike',
            service__pb2.GetLikeRequest.SerializeToString,
            service__pb2.GetLikeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeLikes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/likes.v2.LikesService/SubscribeLikes',
            service__pb2.SubscribeRequest.SerializeToString,
            service__pb2.LikeUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
