replicaCount: 1

image:
  repository: bookings-app
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  name: bookings-svc-s18
  type: ClusterIP
  port: 8292

container:
  name: bookings-container
  port: 8292

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "250m"
    memory: "256Mi"

probes:
  path: /
  initialDelaySeconds: 10
  periodSeconds: 10